async function poll(p,fn,arg){const end=Date.now()+90000;while(Date.now()<end){if(await p.evaluate(fn,arg))return;await p.waitForTimeout(150)}throw Error('browser condition timed out')}
// Local origin, real Chromium Service Worker. Never touches GitHub Pages.
const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert/strict'),{execFileSync}=require('child_process'),{chromium}=require('playwright');
const root=process.env.RESULT_DIR||'/workspace/seaart-stage5-e',repo=path.resolve(__dirname,'..');
const oldHTML=fs.readFileSync(root+'/baseline.html'),newHTML=fs.readFileSync(repo+'/index.html'),oldSW=execFileSync('git',['show','ee5b64accf1cccbe36b2d30284251b32e241c211:sw.js'],{cwd:repo}),newSW=fs.readFileSync(repo+'/sw.js');
const cacheName=newSW.toString().match(/const CACHE_NAME = '([^']+)'/)[1];
let html=newHTML,sw=oldSW,failManifest=false;
const server=http.createServer((req,res)=>{let file=req.url.split('?')[0].replace(/^\/app\//,'');if(!file)file='index.html';const body=file==='index.html'?html:file==='sw.js'?sw:fs.existsSync(repo+'/'+file)?fs.readFileSync(repo+'/'+file):null;if(!body||(file==='manifest.json'&&failManifest)){res.writeHead(503);return res.end('fixture unavailable')}res.writeHead(200,{'Content-Type':file.endsWith('.html')?'text/html;charset=utf-8':file.endsWith('.js')?'application/javascript':file.endsWith('.json')?'application/json':'image/png','Cache-Control':'no-store'});res.end(body)});
const waitReady=p=>p.waitForFunction(()=>actorFormStorageReady&&navigator.serviceWorker.controller);
const disk=p=>p.evaluate(()=>Object.fromEntries(Object.values(actorFormStorageKeys).map(k=>[k,localStorage.getItem(k)])));
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}/app/index.html`,browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']}),checks=[];try{
 // Actual old cache, open old tab, new SW update and migration into isolated keys.
 html=oldHTML;sw=oldSW;const ctx=await browser.newContext(),old=await ctx.newPage();old.on('dialog',d=>d.accept());await old.goto(url,{waitUntil:'domcontentloaded'});await waitReady(old);await old.evaluate(()=>{restoreCreatures([{id:'pwa-e',species:'pikachu (pokemon)'}]);applyActorForm('creature:pwa-e');setCreatureRepresentation('creature:pwa-e','semi');openCreatureHumanEditor('creature:pwa-e','semi');creatureHumanEditorState.byMode.semi.record.faceDirection='facing viewer';creatureHumanEditorState.byMode.full.record.faceDirection='facing left';saveCreatureHumanEditor();clearTimeout(workingSaveTimer);saveCurrentWorking();window.notReloaded='old-tab';openCreatureHumanEditor('creature:pwa-e','semi');creatureHumanEditorState.byMode.semi.record.gaze='looking up'});const native=await old.evaluate(()=>afCopy(creatures)),ext=await old.evaluate(()=>afCopy(actorExtensions));
 html=newHTML;sw=newSW;await old.evaluate(async()=>{await(await navigator.serviceWorker.getRegistration()).update()});await poll(old,async cacheName=>{const keys=await caches.keys();return keys.includes(cacheName)&&!keys.includes('seaart-tool-pwa-v3-20261004')},cacheName);await poll(old,async cacheName=>{const c=await caches.open(cacheName);return !!(await c.match(new URL('./index.html',location.href)))},cacheName);assert.equal(await old.evaluate(async cacheName=>{const c=await caches.open(cacheName);return(await c.match(new URL('./index.html',location.href))).text()},cacheName),newHTML.toString('utf8'));assert.equal(await old.evaluate(()=>window.notReloaded),'old-tab');assert(await old.evaluate(()=>creatureHumanEditorChanged()));console.log('checkpoint',checks.length);checks.push('real old SW → new SW activates / old cache removed / no forced reload or draft loss');
 const fresh=await ctx.newPage();fresh.on('dialog',d=>d.accept());await fresh.goto(url,{waitUntil:'domcontentloaded'});await waitReady(fresh);assert.deepEqual(await fresh.evaluate(()=>creatures),native);assert.deepEqual(await fresh.evaluate(()=>actorExtensions),ext);assert.equal(await fresh.evaluate(()=>resultAccessPermissions.size+creatureAdultAuthorizations.size),0);console.log('checkpoint',checks.length);checks.push('new HTML migrates native / semi / full / applied snapshot without session grants');
 const protectedDisk=await disk(fresh);await fresh.evaluate(()=>{clearTimeout(workingSaveTimer);actorFormStartup.blocked=true});await old.evaluate(()=>{scene.extra='old tab modification';persist();saveCurrentWorking()});assert.deepEqual(await disk(fresh),protectedDisk);console.log('checkpoint',checks.length);checks.push('live old tab writes previous namespace only; destination five bytes unchanged');
 await fresh.reload({waitUntil:'domcontentloaded'});await waitReady(fresh);await ctx.setOffline(true);await fresh.reload({waitUntil:'domcontentloaded'});await waitReady(fresh);assert.deepEqual(await fresh.evaluate(()=>creatures),native);assert.deepEqual(await fresh.evaluate(()=>actorExtensions),ext);console.log('checkpoint',checks.length);checks.push('new cache boots fully offline and restores independent appearances');
 await fresh.evaluate(()=>{setCreatureRepresentation('creature:pwa-e','full');openCreatureHumanEditor('creature:pwa-e','full');creatureHumanEditorState.byMode.full.record.faceDirection='facing viewer';saveCreatureHumanEditor();clearTimeout(workingSaveTimer);saveCurrentWorking()});const offlineExt=await fresh.evaluate(()=>afCopy(actorExtensions));await fresh.reload({waitUntil:'domcontentloaded'});await waitReady(fresh);assert.deepEqual(await fresh.evaluate(()=>actorExtensions),offlineExt);assert.equal(await fresh.evaluate(()=>resultAccessPermissions.size+creatureAdultAuthorizations.size),0);await fresh.evaluate(()=>setCreatureRepresentation('creature:pwa-e','semi'));const semiBeforeDraft=await fresh.evaluate(()=>afCopy(actorExtensions));await fresh.evaluate(()=>{openCreatureHumanEditor('creature:pwa-e','semi');creatureHumanEditorState.byMode.semi.record.gaze='looking down';saveCurrentWorking()});await fresh.reload({waitUntil:'domcontentloaded'});await waitReady(fresh);assert.deepEqual(await fresh.evaluate(()=>actorExtensions),semiBeforeDraft);console.log('checkpoint',checks.length);checks.push('offline edit/save/reload persists; unsaved draft never enters bundle; grants empty');await ctx.close();
 // New code under old controlling worker: failed addAll keeps old worker; retry emits notice.
 html=newHTML;sw=oldSW;const c=await browser.newContext(),p=await c.newPage();await p.goto(url,{waitUntil:'domcontentloaded'});await waitReady(p);await p.evaluate(()=>{window.noReload='retain';window.updateNotices=[];const original=toast;toast=m=>{updateNotices.push(m);return original(m)}});const before=await disk(p);failManifest=true;sw=newSW;await p.evaluate(async()=>{window.failedUpdate=new Promise(async resolve=>{const r=await navigator.serviceWorker.getRegistration();r.addEventListener('updatefound',()=>{const w=r.installing;w.addEventListener('statechange',()=>{if(w.state==='redundant')resolve(true)})},{once:true});await r.update()})});await p.waitForFunction(()=>window.failedUpdate);assert.equal(await p.evaluate(()=>window.noReload),'retain');assert((await p.evaluate(()=>caches.keys())).includes('seaart-tool-pwa-v3-20261004'));assert.deepEqual(await disk(p),before);console.log('checkpoint',checks.length);checks.push('cache.addAll failure keeps old controlling worker and committed storage');failManifest=false;await p.evaluate(async()=>{await(await navigator.serviceWorker.getRegistration()).update()});await poll(p,async cacheName=>{const r=await navigator.serviceWorker.getRegistration();return r.active?.state==='activated'&&(await caches.keys()).includes(cacheName)&&!(await caches.keys()).includes('seaart-tool-pwa-v3-20261004')&&window.updateNotices.some(x=>x.includes('更新の準備'))},cacheName);assert.equal(await p.evaluate(()=>window.noReload),'retain');await c.setOffline(true);await p.reload({waitUntil:'domcontentloaded'});await waitReady(p);console.log('checkpoint',checks.length);checks.push('retry installs new cache / update notice / no forced reload / offline startup');await c.close();
 fs.writeFileSync(root+'/sw-update-results.json',JSON.stringify({passed:true,checks,realChromium:true,realServiceWorker:true,offlineNavigation:true,publicPages:false,physicalDeviceRestart:false},null,2));console.log('PASS SW update '+checks.length+' checks');
}finally{await browser.close();server.close()}})().catch(e=>{console.error(e.stack);server.close();process.exitCode=1});
